on:
  rss:
    # url: https://dev.to/feed/this-is-learning
    url: https://dev.to/feed/tag/javascript

jobs:
  Tweet:
    name: Tweet
    runs-on: ubuntu-latest
    steps:
      - name: categories to tags
        uses: actions/github-script@v4
        id: categories-to-tag
        env:
          categories: ${{ on.rss.outputs.categories }}
        with:
          script: |
            if(!process.env?.categories) {
              return "";
            }
            console.log(process.env?.categories);
            console.log(typeof process.env?.categories);
            return JSON.parse(process.env.categories).map(t => `#${t}`).join(" ");
          result-encoding: string
      - name: Debug and Echo Results
        run: echo "${{steps.categories-to-tag.outputs.result}}" 
      - name: Post to This is Learning
        uses: ethomson/send-tweet-action@v1
        with:
          status: |
            "${{ on.rss.outputs.title }}" by ${{ on.rss.outputs.author }}
            ${{steps.categories-to-tag.outputs.result}}
            ${{ on.rss.outputs.link }}
          consumer-key: ${{ secrets.TIL_TWITTER_CONSUMER_KEY }}
          consumer-secret: ${{ secrets.TIL_TWITTER_CONSUMER_SECRET }}
          access-token: ${{ secrets.TIL_TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TIL_TWITTER_ACCESS_SECRET }}
