on:
  rss:
    url: https://dev.to/feed/this-is-angular

jobs:
  Tweet:
    name: Tweet
    runs-on: ubuntu-latest
    steps:
      - name: Post To This is Angular
        uses: ethomson/send-tweet-action@v1
        with:
          status: |            
            "${{ on.rss.outputs.title }}" by ${{ on.rss.outputs.author }} 
            #${{ join(on.rss.outputs.category, ' #') }}
            ${{ on.rss.outputs.link }}
          consumer-key: ${{ secrets.TWITTER_CONSUMER_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_SECRET }}