on:
  rss:
    url: https://dev.to/feed/this-is-learning

concurrency: this-is-angular-rss

jobs:
  tweet:
    name: Tweet article
    runs-on: ubuntu-latest
    steps:
      - name: Tweet about article
        uses: ./actions/tweet-article
        with:
          rss-author: ${{ on.rss.outputs.author }}
          rss-categories: ${{ on.rss.outputs.categories }}
          rss-link: ${{ on.rss.outputs.link }}
          rss-title: ${{ on.rss.outputs.title }}
          twitter-authentication-access-token: ${{ secrets.TIA_TWITTER_ACCESS_TOKEN }}
          twitter-authentication-access-token-secret: ${{ secrets.TIA_TWITTER_ACCESS_SECRET }}
          twitter-consumer-api-key: ${{ secrets.TIA_TWITTER_CONSUMER_KEY }}
          twitter-consumer-api-key-secret: ${{ secrets.TIA_TWITTER_CONSUMER_SECRET }}
