on:
  rss:
    url: https://dev.to/feed/this-is-learning

jobs:
  Tweet:
    name: Tweet
    runs-on: ubuntu-latest
    steps:
      - name: Post to This is Learning
        uses: ethomson/send-tweet-action@v1
        with:
          status: |
            "${{ on.rss.outputs.title }}" by ${{ on.rss.outputs.author }}
            ${{ on.rss.outputs.link }}
          consumer-key: ${{ secrets.TIL_TWITTER_CONSUMER_KEY }}
          consumer-secret: ${{ secrets.TIL_TWITTER_CONSUMER_SECRET }}
          access-token: ${{ secrets.TIL_TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TIL_TWITTER_ACCESS_SECRET }}
