on:
  rss:
    url: https://dev.to/feed/this-is-angular

jobs:
  Tweet:
    name: Tweet
    runs-on: ubuntu-latest
    steps:
      - name: categories to tags
        uses: actions/github-script@v4
        id: categories-to-tag
        env:
          categories: ${{ on.rss.outputs.categories }}
          TIA_HASHTAG: ${{ secrets.TIA_HASHTAG }}
        with:
          script: |
            if(!process.env?.categories) {
              return `${process.env.TIA_HASHTAG}`;
            }
            const categoriesHashTags = process.env.categories.split(",").map(t => `#${t}`).join(" ");
            return `${categoriesHashTags} ${process.env.TIA_HASHTAG}`;
          result-encoding: string
      - name: Post To This is Angular
        uses: ethomson/send-tweet-action@v1
        with:
          status: |            
            "${{ on.rss.outputs.title }}" by ${{ on.rss.outputs.author }} ${{steps.categories-to-tag.outputs.result}}
            ${{ on.rss.outputs.link }}
          consumer-key: ${{ secrets.TIA_TWITTER_CONSUMER_KEY }}
          consumer-secret: ${{ secrets.TIA_TWITTER_CONSUMER_SECRET }}
          access-token: ${{ secrets.TIA_TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TIA_TWITTER_ACCESS_SECRET }}