on:
  rss:
    url: https://dev.to/feed/this-is-learning

jobs:
  Tweet:
    name: Tweet
    runs-on: ubuntu-latest
    steps:
      - name: categories to tags
        uses: actions/github-script@v6
        id: categories-to-tag
        env:
          categories: ${{ on.rss.outputs.categories }}
        with:
          script: |
            if(!process.env?.categories) {
              return "";
            }
            const categoriesHashTags = process.env.categories.split(",").map(t => `#${t}`).join(" ");
            return `${categoriesHashTags}`;
          result-encoding: string
      - name: Post to This is Learning
        uses: ethomson/send-tweet-action@v1
        with:
          status: |
            "${{ on.rss.outputs.title }}" by ${{ on.rss.outputs["dc:creator"] }} ${{steps.categories-to-tag.outputs.result}} #ThisIsLearning
            ${{ on.rss.outputs.link }}
          consumer-key: ${{ secrets.TIL_TWITTER_CONSUMER_KEY }}
          consumer-secret: ${{ secrets.TIL_TWITTER_CONSUMER_SECRET }}
          access-token: ${{ secrets.TIL_TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TIL_TWITTER_ACCESS_SECRET }}
